version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      # Install Android SDK
      - wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk.zip
      - unzip -qq android-sdk.zip -d $HOME/android-sdk
      - echo 'export ANDROID_HOME=$HOME/android-sdk' >> $BASH_ENV
      - echo 'export PATH=$PATH:$ANDROID_HOME/tools/bin' >> $BASH_ENV
      - echo 'export PATH=$PATH:$ANDROID_HOME/platform-tools' >> $BASH_ENV
      - source $BASH_ENV
      - yes | sdkmanager --licenses
      
  pre_build:
    commands:
      # Set up Gradle
      - cd /app/src/
      - chmod +x ./gradlew
      
  build:
    commands:
      # Build the Android app
      - ./gradlew assembleRelease
      
artifacts:
  files:
    - "Tic-Tac-Toe/app/build/outputs/**/*.apk"
